name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d3831681447d5cdbbb686155aaa2680dba8c5445c97de1a19b3c7a6d53ffb80"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
