name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9ca0f6a304d045b0c8bd29fab559f8be143a91c8b803820b49d0a97b955983f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
