name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.13.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2c74cb0aa32391019ced214b291e2f305c75333827e445861e8f96c52346fdb"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
