name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c13d50043ee8695650e3f0d138dd80c59fe01c2c1765c230a30074ec8bfcc97"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
