name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.6.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "943c6334069f24c760d0d9fc06e176cf0f42f328c8463d9f498ca8e90d9cbe25"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
