name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bca1bf2488359a315ccda95aac9ccb36a68206b13c4f12600bd3e6371415c553"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
