name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44341505abae654cf4db87d7cb4a6dfb16a97e885e52549faf9c10cf99f3f577"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
