name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6acf091236162d33aff071713f45acdb3f64a55e801538d5d18354f3a81e2c5d"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
