name = "Mid-Life Crisis"
author = "@mannie-exe"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "788edad1460418dec48aa51454c6794a685674a38dcb55bf2e778e0c615474d3"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
